# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
# https://docs.github.com/actions/learn-github-actions
# https://github.com/actions/upload-artifact
name: build
'on':
  push:
    branches:
      - main
      - dev
      - test

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

permissions: {}

env:
  CW_MAP: '1'
  CW_JOBS: '5'
  CW_CURL_TEST: '1'
  DO_NOT_TRACK: '1'

jobs:
  win-gcc:
    name: 'win-gcc'
    runs-on: ubuntu-26.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: '300'
      - name: 'build'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CW_LLVM_MINGW_DL: '1'
          CW_LLVM_MINGW_ONLY: '0'
        run: |
          export CW_CONFIG="${GITHUB_REF_NAME}-werror-win-gcc"
          export CW_REVISION="${GITHUB_SHA}"
          . ./_versions.sh
          sudo podman image trust set --type reject default
          sudo podman image trust set --type accept docker.io/library
          time podman pull "${OCI_IMAGE_DEBIAN_TESTING}"
          podman images --digests
          time podman run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|SIGN_|COSIGN_|MINISIGN_|GITHUB_|DO_NOT_TRACK)') \
            "${OCI_IMAGE_DEBIAN_TESTING}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: cat urls.txt ./*-version-*.txt || true
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: 'curl-windows-gcc-x64'
          retention-days: ${{ github.ref_name == 'main' && 90 || 5 }}
          path: |
            *-*-mingw*.*
            urls.txt
