# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
# https://docs.github.com/actions/learn-github-actions
# https://github.com/actions/upload-artifact
name: build
on:
  push:
    branches:
      - main
      - dev
      - test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  CW_MAP: '1'
  CW_JOBS: '4'
  DO_NOT_TRACK: '1'
  DOCKER_CONTENT_TRUST: '1'

jobs:
  win-gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 8
      - name: 'build'
        env:
          CW_LLVM_MINGW_DL: '1'
          CW_LLVM_MINGW_ONLY: '0'
        run: |
          export CW_CONFIG='${{ github.ref_name }}-win-gcc-x86-msvcrt-pico-osnotls-libressl'
          export CW_REVISION='${{ github.sha }}'
          . ./_versions.sh
          docker trust inspect --pretty "${DOCKER_IMAGE}"
          time docker pull "${DOCKER_IMAGE}"
          docker images --digests
          time docker run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|GITHUB_|DO_NOT_TRACK)') \
            "${DOCKER_IMAGE}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: cat urls.txt
      - uses: actions/upload-artifact@v4
        with:
          name: 'curl-windows-gcc-noarm64'
          retention-days: 5
          path: |
            *-*-mingw*.*
            urls.txt
